language: php
php:
  - 5.5
  - 5.6

addons:
  code_climate:
    repo_token: c9e47022796dcebc88c36be1f2497e167b12d93f3601619150ceaec39faf520f

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/test-reporter

